#!/usr/bin/env python3

import argparse
import itertools
import os
import subprocess
from difflib import SequenceMatcher
from pathlib import Path


def main(tap_name: str):
    tap_dir = "Library/Taps"
    prefixes = [Path("/opt/homebrew"), Path("/usr/local/Homebrew"), Path("/home/linuxbrew/.linuxbrew")]
    tap_names = [tap_name, tap_name.replace("/", "/homebrew-")]

    paths = itertools.product(prefixes, tap_names)

    for prefix, tap in paths:
        tap_path = prefix / tap_dir / tap
        if tap_path.exists():
            os.chdir(tap_path)
            subprocess.run(["$SHELL"], shell=True)
            break
    else:
        similar_taps = set()

        all_taps = subprocess.run(["brew", "tap"], capture_output=True).stdout.decode().splitlines()
        if all_taps:
            for tap in all_taps:
                if SequenceMatcher(None, tap_name, tap).ratio() > 0.5:
                    similar_taps.add(tap)

        print(f'Tap "{tap_name}" not found.', end='')
        if similar_taps:
            print(" Did you mean:")
            for tap in similar_taps:
                print(tap)

        exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Change the current working directory to a Homebrew tap.")
    parser.add_argument("tap", help="The tap to change the current working directory to.")
    args = parser.parse_args()
    main(args.tap)
